sculpin_content_types:
    posts:
        enabled: false
    talks:
        permalink: talks/:year/:month/:day/:filename/
sculpin_twig:
    extensions:
        - ''
        - html
        - twig
        - json
        - html.twig
        - twig.html
